AzureStorageDemo/Models/Photo.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace AzureStorageDemo.Models
{
    public class Photo
    {
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [DisplayName("Picture")]
        public string ImageName { get; set; }

        [HiddenInput(DisplayValue = false)]
        public string ImageMimeType { get; set; }

        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [Display(Name = "Upload")]
        [Required(ErrorMessage = "Please select a picture")]
        [NotMapped]
        public IFormFile PhotoAvatar { get; set; }

        public byte[] PhotoFile { get; set; }

        [DataType(DataType.DateTime)]
        [DisplayName("Created Date")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yy}", ApplyFormatInEditMode = true)]
        public DateTime CreatedDate { get; set; }
    }
}

AzureStorageDemo/Controllers/BlobController.cs
using System;
using System.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using System.IO;
using AzureStorageDemo.Models;
using AzureStorageDemo.Data;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;

namespace AzureStorageDemo.Controllers
{
    public class BlobController : Controller
    {
        private IConfiguration _configuration;
        private string _connectionString;
        private PhotoContext _dbContext;

        public BlobController(IConfiguration configuration, PhotoContext dbContext)
        {
            _dbContext = dbContext;
            _configuration = configuration;
            _connectionString = _configuration.GetConnectionString("AzureStorageConnectionString-1");
        }

        [HttpGet]
        public IActionResult CreateImage()
        {
            return View();
        }


        [HttpPost, ActionName("CreateImage")]
        public async Task<IActionResult> CreateImageAsync(Photo photo)
        {
            if (ModelState.IsValid)
            {
                photo.CreatedDate = DateTime.Today;
                if (photo.PhotoAvatar != null && photo.PhotoAvatar.Length > 0)
                {
                    photo.ImageMimeType = photo.PhotoAvatar.ContentType;
                    photo.ImageName = Path.GetFileName(photo.PhotoAvatar.FileName);
                    using (var memoryStream = new MemoryStream())
                    {
                        photo.PhotoAvatar.CopyTo(memoryStream);
                        photo.PhotoFile = memoryStream.ToArray();
                    }
                    await UploadAsync(photo.PhotoAvatar);
                    _dbContext.Add(photo);
                    _dbContext.SaveChanges();
                    return RedirectToAction("Index", "Home");
                }
                return View(photo);
            }
            return View(photo);
        }
        public async Task UploadAsync(IFormFile photo)
        {
            CloudStorageAccount storageAccount = CloudStorageAccount.Parse(_connectionString);
            CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();
            CloudBlobContainer container = blobClient.GetContainerReference("myfirstcontainer");

            if (await container.CreateIfNotExistsAsync())
            {
                await container.SetPermissionsAsync(
                new BlobContainerPermissions
                {
                    PublicAccess = BlobContainerPublicAccessType.Blob
                });
            }
            CloudBlockBlob blob = container.GetBlockBlobReference(Path.GetFileName(photo.FileName));
            await blob.UploadFromStreamAsync(photo.OpenReadStream());
        }

    }
}

AzureStorageDemo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AzureStorageDemo.Data;
using AzureStorageDemo.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

namespace AzureStorageDemo.Controllers
{
    public class HomeController : Controller
    {
        private PhotoContext _dbContext;
        private IHostingEnvironment _environment;

        public HomeController(PhotoContext dbContext, IHostingEnvironment environment)
        {
            _dbContext = dbContext;
            _environment = environment;
        }

        public IActionResult Index()
        {
            return View(_dbContext.Photos.ToList());
        }

        public IActionResult GetImage(int id)
        {
            Photo requestedPhoto = _dbContext.Photos.FirstOrDefault(i => i.Id == id);
            if (requestedPhoto != null)
            {
                string webRootpath = _environment.WebRootPath;
                string folderPath = "\\images\\";
                string fullPath = webRootpath + folderPath + requestedPhoto.ImageName;
                if (System.IO.File.Exists(fullPath))
                {
                    FileStream fileOnDisk = new FileStream(fullPath, FileMode.Open);
                    byte[] fileBytes;
                    using (BinaryReader br = new BinaryReader(fileOnDisk))
                    {
                        fileBytes = br.ReadBytes((int)fileOnDisk.Length);
                    }
                    return File(fileBytes, requestedPhoto.ImageMimeType);
                }
                else
                {
                    if (requestedPhoto.PhotoFile.Length > 0)
                    {
                        return File(requestedPhoto.PhotoFile, requestedPhoto.ImageMimeType);
                    }
                    else
                    {
                        return NotFound();
                    }
                }
            }
            else
            {
                return NotFound();
            }
        }
    }
}

AzureStorageDemo/Views/Blob/CreateImage.cshtml
@model AzureStorageDemo.Models.Photo

@{
    ViewData["Title"] = "CreateImage";
}

<div class="add-image">
    <h1 class="into">Add Photo to Album</h1>
    <div class="row justify-content-center">
        <div class="col-4">
            <form method="post" enctype="multipart/form-data" asp-action="CreateImage">
                <div class="form-group row">
                    <label asp-for="Title" class="col-sm-4 col-form-label"></label>
                    <div class="col-sm-6">
                        <input asp-for="Title" type="text" class="form-control" placeholder="Photo Title" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Description" class="col-sm-4 col-form-label"></label>
                    <div class="col-sm-6">
                        <input asp-for="Description" type="text" class="form-control" placeholder="Photo Description" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="PhotoAvatar" class="col-sm-4 col-form-label"></label>
                    <div class="col-sm-6">
                        <input asp-for="PhotoAvatar" type="file" class="form-control" placeholder="file" required>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-outline-primary">
                            Submit Photo to Azure
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


@section Scripts {
    <script src="~/node_modules/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/node_modules/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>
}

AzureStorageDemo/Views/Home/Index.cshtml
@model IEnumerable<AzureStorageDemo.Models.Photo>

@{
    ViewData["Title"] = "Index";
}

<h1 class="into">My Photo Album</h1>
<h2 class="into">Latest Memories</h2>
<button type="button" class="btn btn-info" onclick="location.href='@Url.Action("CreateImage", "Blob")'">Upload New Image</button>
<br />
@foreach (var item in Model)
{
    <div class="photo-index-card">
        <h3 class="display-picture-title">
            @Html.DisplayFor(modelItem => item.Title)
        </h3>
        @if (item.ImageName != null)
        {
            <div class="photo-display">
                <img class="photo-display-img" src="@Url.Action("GetImage", "Home", new { Id = item.Id })" />
            </div>
        }

        <div>
            <span class="display-label">
                @Html.DisplayNameFor(model => model.Description):
            </span>
            <br />
            <span class="display-field">
                @Html.DisplayFor(model => item.Description)
            </span>
        </div>

        <div>
            <span class="display-label">
                @Html.DisplayNameFor(model => model.CreatedDate):
            </span>
            <span class="display-field">
                @Html.DisplayFor(model => item.CreatedDate)
            </span>
        </div>
    </div>
}

AzureStorageDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/photo-album-styles.css" rel="stylesheet" />
    <script src="~/node_modules/jquery/dist/jquery.min.js"></script>
    <script src="~/node_modules/popper.js/dist/umd/popper.min.js"></script>
    <script src="~/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    @RenderSection("Scripts", false)
</body>
</html>